steps:
  # Build Web Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-web'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digest-web:${COMMIT_SHA:0:7}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digest-web:latest'
      - '-f'
      - 'Dockerfile.web'
      - '.'

  # Build Jobs Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-jobs'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digest-jobs:${COMMIT_SHA:0:7}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digest-jobs:latest'
      - '-f'
      - 'Dockerfile.jobs'
      - '.'

  # Push Web Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-web'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/digest-web'
    waitFor: ['build-web']

  # Push Jobs Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-jobs'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/digest-jobs'
    waitFor: ['build-jobs']

images:
  - 'gcr.io/$PROJECT_ID/digest-web'
  - 'gcr.io/$PROJECT_ID/digest-jobs'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
